### ISSUE TITLE
Error: WebGL warning: Requested size was too large...

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstone#140]
Hi, I'm getting this error on Firefox 54 Linux 64bits (but on previous versions the error is also raised), when trying to open big images (for example 3500x4200 CR image)

```Error: WebGL warning: Requested size 3520x4280 was too large, but resize to 1760x2140 succeeded```

Do you plan a fallback mechanism for these cases?.

**Comment by swederik** [comment]
Good question. I have never encountered it... I guess we need to figure out what to do in these cases.

**Comment by dannyrb** [comment]
@leonardorame do you have an anonymized example image you can provide. I don't have any CR's that large floating around.

**Comment by leonardorame** [comment]
Hi @dannyrb, please try with the attached example.

[example.zip](https://github.com/cornerstonejs/cornerstone/files/1822062/example.zip)

**Comment by dannyrb** [comment]
Hi @leonardorame, are you seeing this issue in FF latest?

When I update the `cornerstoneWADOImageLoader` to use the `webgl` renderer from the console, and then load in your example image, I am unable to reproduce your issue.

![image](https://user-images.githubusercontent.com/5797588/54874453-10102b00-4dc2-11e9-9a06-0ab73f6975b5.png)

![image](https://user-images.githubusercontent.com/5797588/54874463-21f1ce00-4dc2-11e9-829d-c4dbd1910193.png)

If you're able, can you provide a screenshot or minimal reproduction? I'm unsure of how to proceed at this point. I'll mark this as closed unless I hear back. This issue was raised in 2017 and may no longer apply.
