### ISSUE TITLE
A place to post sample viewers created with this library?

### ISSUE THREAD

**Issue by tlacaelelrl** [cornerstonejs/cornerstone#204]
Is there a place to showcase viewers that have been created with cornerstone?

If not I think that having one will also allow others to see what can be done and also provide ideas on how to implement viewers.

In the test viewers I sometimes found code that provides examples on how to implement some features that are not necesarily dcumented or are missing pieces of documentation.

**Comment by dannyrb** [comment]
I _think_ we're trying to avoid including viewer source code in a `CornerstoneJS` repository, because it feels like we'd need to "maintain" or update that code as we move forward. We're currently resource constrained, so the best we could probably do is keep a list of open source / example viewers?

I have a couple very simple proof of concepts I've built to help others:

_VueJS_
- https://dannyrb.github.io/cornerstone-vuejs-poc/#/
- https://github.com/dannyrb/cornerstone-vuejs-poc/blob/master/src/components/CornerstoneCanvas.vue

_Angular_
- https://github.com/dannyrb/cornerstone-angular-poc


The OHIF Viewer is a more advanced example built with Meteor:

- http://viewer.ohif.org/
- https://github.com/OHIF/Viewers


There are also a decent number of live examples of tools/functionality in the `cornerstoneTools` repository that are actively maintained:

- https://rawgit.com/cornerstonejs/cornerstoneTools/master/examples/index.html
- https://github.com/cornerstonejs/cornerstoneTools

I'd be curious to hear any thoughts you have on documentation and example implementations. We are in the middle of revamping our documentation to be cleaner and would love any/all help we can get. You can see the beginnings of it:

- Here: https://tools.cornerstonejs.org/
- And the related GitHub issue:  https://github.com/cornerstonejs/cornerstoneTools/issues/300

If you have any thoughts @swederik, please feel free to chime in

**Comment by tlacaelelrl** [comment]
I did not know you were working on that documentation, looks like is what is definitely needed, I always had a hard time finding how to do certain things.

And, is there a way to help on that documentation, I could help on the things I already learned, so if you need any let me know.

Here is my implementation of the [viewer](https://platform.v2.vetology.net/patient-manager?id=eyJpdiI6IlZOZWh0ckNmcXVXTXVINFBibFFlZVE9PSIsInZhbHVlIjoidDdhZThYOGRuYjRZSGRoY3orMWJcL1dDMXJRRUdUZXA1UW43VUpNbUpQK0dEZ2lOY25PYUJvaTdlSzlwTFRIdWNVV1lhWmpic29MbVgxZFpxVnRydFBtbXdRMElnbkxSRXozczNWQXJ0eWk5d0UxdEJpcHFvYXZMYVZqc1dzNzBqK1h1d1JoWGl4dDVtbVJVYUtBeXFtNEFJbTJjNnVmUTE2WmIwajhwU3ptaz0iLCJtYWMiOiIyZGYxYmE4OGM1MjA3NzIzZDYxMTIzZTI4MzkwYTY0NGQ3OGJlODJlNTRlZTAwZDUwOTg4MzMwMTExYjliZDUwIn0=&view=iv)

**Comment by dannyrb** [comment]
Thanks for providing a link to your viewer. I'll talk to @swederik about creating a space for providing example open/closed source viewers.

If you're interested in contributing, you can click the "Edit This Page" link at the top of any page in this set of documentation: https://tools.cornerstonejs.org/

- "Edit this page"
- Make your changes
- Select "Create a new branch for this commit and start a pull request."

If you want to add a new page, or think we're missing an important example, create a new issue and we can discuss options. If you have a good understanding of Git, pull requests, etc. The docs are generated from the `docs/` section, and are essentially just markdown pages: 

https://github.com/cornerstonejs/cornerstoneTools/tree/master/docs

We'll spin up docs for the other repositories before too long. Right now, only CornerstoneTools has the new version
