### ISSUE TITLE
What are the plans for cancelFn?

### ISSUE THREAD

**Issue by freund17** [cornerstonejs/cornerstone#209]
In https://github.com/cornerstonejs/cornerstone/commit/9448755397da10a6de6f694d83123274cbd4b38e, `cancelFn` was added to `imageLoadObject` in `ImageCache` https://github.com/cornerstonejs/cornerstone/blob/master/src/imageCache.js#L76

When it is going to be used?
Maybe in `removeImageLoadObject` or `decache`?
It should also get forwarded by `loadImage` and `loadAndCacheImage`. So it could be used by -- for example -- `requestPoolManager` from `cornerstoneTools`.

**Comment by dannyrb** [comment]
@freund17, a lot of additions find there way in because a 3rd party using the library made a PR, and provided a good enough reason for the addition of a hook / api. If we had a specific reason, @swederik would be the best person to ask. Over the next few months, we'll be taking a harder look at how/what we expose and allow hooks into. Keep your eyes open as we spin up a few working groups, and begin taking a more deliberate approach to extending/growing Cornerstone..

**Comment by swederik** [comment]
Yes the goal is to be able to cancel requests the user no longer needs. So, for example, if you switch studies you can cancel everything ongoing (and clear the request pool) for the previous study. We haven't gotten around to implementing it in the WADO Image Loader yet, but that would be the first step.

As for where it applies in core / tools, I'm not sure yet, but I kind of feel like it should be explicitly called by the application because otherwise we are going to end up with some crazy bugs (I believe this was @diego0020's comment on the other thread).

**Comment by diego0020** [comment]
This is the mentioned thread https://github.com/cornerstonejs/cornerstone/pull/184
