### ISSUE TITLE
JPEG leveling differs from DICOM leveling

### ISSUE THREAD

**Issue by swj54** [cornerstonejs/cornerstone#344]
In order to improve the loading speed, I converted WADO into JPG, but the effect of adjusting windowWidth and windowCenter is not consistent with WADO. How to solve this problem?

I noticed that renderWebImage was not executed when the window level was adjusted, and renderColorImage was used.

**Comment by dannyrb** [comment]
`renderWebImage` is only used for the initial window levels; then the `renderColorImage` is used 🤷‍♂️ 

DICOMs converted to JPEG are usually renderings with a specific level applied. When JPEGs are created this way, you often see a loss of data. This will likely be most noticeable for CT images when applying window level presets.

The web image loader is faster, but usually because you're not sending a lossless representation of the image data. Some teams get around this be either:

- Sticking w/ WADO loader, but converting DICOMs w/ slower formats to a different lossless format supported by the WADO loader
- Using a modified version of the web image loader where images are a combination of 8/16-bit Grayscale PNGs and color JPEGs.
