### ISSUE TITLE
Black zones (pixels) in the picture

### ISSUE THREAD

**Issue by jcarreno** [cornerstonejs/cornerstone#508]
Some pictures have black zones. I can open the same pictures in other viewers without problem.

![image](https://user-images.githubusercontent.com/1453472/110359007-442b9780-803d-11eb-83dd-b541c326e1f8.png)

The file is here:

https://we.tl/t-hMlHNDqG4V

Thank you!

**Comment by chafey** [comment]
The issue is that the DICOM file says the smallestPixelValue (x00280106) is 13731 and this it is actually smaller.  The result is the values less than what is specified are displayed as black since values outside the dynamic range are returned as undefined or 0 and thus rendered black.  You can workaround this by providing your own metaDataProvider that returns undefined for x00280106 and x00280107 which will cause cornerstone to manually calculate the smallest and largest pixel values

**Comment by jcarreno** [comment]
Thank you so much! It works beautiful!

**Comment by silencej** [comment]
Maybe a better solution is to disable the `strict` in the webWorker:

```
try {
  cornerstoneWADOImageLoader.webWorkerManager.initialize({
    maxWebWorkers: navigator.hardwareConcurrency || 1,
    startWebWorkersOnDemand: true,
    webWorkerTaskPaths: [],
    taskConfiguration: {
      decodeTask: {
        initializeCodecsOnStartup: true,
        // strict: true,
        strict: false,
      },
    },
  });
  cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
  cornerstoneWADOImageLoader.external.dicomParser = dicomParser

  // cornerstone.metaData.addProvider(metaDataProvider);

} catch (error) {
  throw new Error('cornerstoneWADOImageLoader is not loaded');
}
```
