### ISSUE TITLE
AddLayer Multiple Images

### ISSUE THREAD

**Issue by ArturRod** [cornerstonejs/cornerstone#560]
Hello, I wanted to know if it is possible to add multiple images to a layer, since I want to perform the CT / PET fusion, like this example:
https://rawgit.com/cornerstonejs/cornerstone/master/example/layers/index.html

The thing is, this only allows a single image, and I would like to add a stack of data.
`let layer1 = cornerstone.addLayer(
        element,
        imagesLayer1,
        layer1Options.options
      );`

I tried to get it to work but the addLayer method does not allow multiple images, any ideas or solutions?

**Comment by shanebenlolo** [comment]
Is there a reason you need to perform fusion in the cornerstone viewport? If not, you can perform fusion using react-vtkjs-viewport. See this example for details https://react-vtkjs-viewport.netlify.app/fusion

**Comment by ArturRod** [comment]
Hi @shanebenlolo.
The problem with this is that it generates the views in 3D, I was trying to find something like this:
http://www.dvisionlab.com/Larvitar/examples/layers.html

**Comment by shanebenlolo** [comment]
You may have an easier time duplicating the MPR view offered in OHIF:

![91012743-ef3cac80-e629-11ea-9843-7707fb60ebf8](https://user-images.githubusercontent.com/66500087/141820291-e51cf3b3-109a-4915-861c-0c721c2cd818.png)
 

but have it render only one vtk viewport (the left view) rather than three. You can also remove the crosshairs if you wish. This should give a 2D view that you are looking for. This code will probably be much easier to write than the code required to get the layers api to work for this task.

**Comment by ArturRod** [comment]
Hi @shanebenlolo !
Thank you very much, the truth had not occurred to me to do it like that, I'm going to see how it turns out.

**Comment by shanebenlolo** [comment]
Glad I could help :)
