### ISSUE TITLE
Conversion of Dicom Image to Base64  and Downloading of Dicom Images

### ISSUE THREAD

**Issue by vivek00712** [cornerstonejs/cornerstone#80]
please tell me how can i get image108Base64 **encoder** and **decoder** because i want to store images in my SQL Database so i can retrieve and store it into database if i have image in base64 formate.
So kindly guide me how to set image108Base64 for dicom image that you explain in your example by defining static set of image with image108Base64 formate.
In which format you are giving value to image108Base64 and image109Base64 variable

And if i have multiple images in my canvas that i am referring on my mouse scroll and i want to download all the images on single click at **particular user define location**  in **dicom** format only than what should i have to do.

Please do the needfull
Thanks in Advance
Vivek

**Comment by onluiz** [comment]
Hi! I'm just interested on it, too.

I want to convert a .dcm file to base64, since I'm developing a javafx aplication and cornerstone (js) can't read local files.

I'd tried some normal image-to-base64 examples but none of them is converting .dcm properly.

I would be grateful if you can explain how to do this convertion with .dcm files, like you do in cornerstone examples.

Thanks in advance.

**Comment by FMCalisto** [comment]
I also have the same question.

**Comment by muthupriyabse** [comment]
Hello @chafey , @vivek00712 , @FMCalisto ,@swederik 
i also facing same problem , i tried some method but i cant get the output , i have some 16bit grayscale images and i convert as a base64 and i assigned that value in this "image108Base64" but its not work, i get some sparkle images like this http://prntscr.com/g31fb4 , what is procedure for "image108Base64" value , how can we create the value for this variable. please help us to fix this issues.

**Comment by pchiarato** [comment]
Did anyone solve this problem, I'm on the same boat. Thanks

**Comment by dannyrb** [comment]
Technically speaking, this isn't a great approach. I believe base64 encoding increases file sizes by 33%, you'd be bloating your DB, and you'd hit some speed/performance issues when encoding/decoding.

That being said, there shouldn't be any crazy technical hurdles to accomplishing this.

- Controller encodes DICOM to base64, stores in DB
- Controller grabs base64 representation of DICOM from DB, decodes, passes down original file

Unless I'm missing something (entirely possible), this should all work well enough with the `cornerstoneWADOImageLoader`. It doesn't care what happens on your server, so long as the endpoint it hits returns a DICOM file.

If you want to pass down the base64 encoded version, you'd likely need to modify the existing image loader to decode the image before using it. I don't think we support base64 encoded images as a type, but I may be mistaken.

**Comment by pchiarato** [comment]
@dannyrb Thanks for replying so quickly, I'm working on a angular 2 project and am trying to display a .dcm file using a component. The .dcm file is on a fileshare structure not on a DB. I was not able to find any recent example of a simple dicom image being displayed using angular 2/4 I was able to display an image by using the base64 code that was at this url https://rawgit.com/cornerstonejs/cornerstone/master/example/exampleImageIdLoader.js hence why I was looking for a way to maybe in node pass the file to a function that would convert to base64 so cornerstone could display it. I thought cornerstoneWADOImageLoader was very confusing and it looked like it was expecting the file to be fed from an URL. Do you know of anything or can you point me on the right direction? thank you

**Comment by dannyrb** [comment]
I have a rough, not maintained, Angular POC repo located here:
https://github.com/dannyrb/cornerstone-angular-poc

cornerstoneWADOImageLoader can be used to load `DICOM` images that can be accessed via a URL. If it's setup and configured correctly, you load your image by prefixing the URL when you call `.loadImage`

For Example:

```
var imageUrl = 'http://www.example.com/path/to/myFile.dcm'
var imageId = 'wadouri:' + imageUrl
cornerstone.loadAndCacheImage(imageId).then(function(image) {
...
}
```

The `wadouri:` prefix tells cornerstone which image loader to use. The `cornerstoneWebImageLoader` can load PNG/JPEG images, and looks for the `https:` and `http:` prefixes.

**Comment by dannyrb** [comment]
It looks like my POC may be a major version behind, but it should be easy to tweak it to work with latest. I believe it's only missing the changes that dropped jQuery support:

_Setup_: https://github.com/dannyrb/cornerstone-angular-poc/blob/master/src/app/cornerstone/cornerstone.component.ts#L1-L31

_Loading a DICOM image_: https://github.com/dannyrb/cornerstone-angular-poc/blob/master/src/app/cornerstone/cornerstone.component.ts#L1-L31

If you're worried about auth, you can put your images behind a protected route and then use an authorization header to give the image loader access

**Comment by dannyrb** [comment]
## Overview of Image Loaders

1. You register an image loader that should be used when an `imageId` starts with a specific `scheme`. Here's the simplest example:

```
cornerstone.registerImageLoader('http', cornerstoneWebImageLoader.loadImage)
cornerstone.registerImageLoader('https', cornerstoneWebImageLoader.loadImage)
```

Where the `scheme` is really just a string, and the "imageLoader" is really any function that returns an image object in this format: [example image object](https://github.com/cornerstonejs/cornerstoneWebImageLoader/blob/master/src/createImage.js#L57-L79)

2. So.. The imageId is whatever input the imageLoader needs to consistently and reliably return the same image object. For the `CornerstoneWebImageLoader`, it's often something as simple as:

`https://my-example-website.com/imageId=some-unique-id-value`

But again, anything URL that would return a JPEG or PNG image.

By default, the `CornerstoneWADOImageLoader` works in a similar way, only instead of prefixing URLs with `https` or `http`, the `wadouri` loader uses [the following schemes](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/4e6c7bdce5c523ebf57b36205e9efafe2f323655/src/imageLoader/wadouri/register.js#L6-L8)

- wadouri
- dicomweb
- dicomfile

While the wadors loader uses [only the `wadors` scheme](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/4e6c7bdce5c523ebf57b36205e9efafe2f323655/src/imageLoader/wadors/register.js#L6)


### Summary

- An image loader is a function that returns an image object
- You can register an image loader to be associated with a `scheme` like `http` or `https`
- The `scheme` is used to tell Cornerstone which loader to use when you pass an imageId to `loadImage`

It may all feel like magic, but when you pull back the covers, it's actually really simple. Let me know if you need more guidance @rahulbhatia123

**Comment by rahulbhatia123** [comment]
Could you help me with an example code for this? I am kinda lost at the image loader part 

![screenshot 2018-06-22 11 53 38](https://user-images.githubusercontent.com/22156512/41761007-6985ca46-7613-11e8-8e99-0fa2f7888a4b.png)
![screenshot 2018-06-22 11 53 55](https://user-images.githubusercontent.com/22156512/41761008-69b9ec0e-7613-11e8-95c5-486d29cef8ff.png)
![screenshot 2018-06-22 11 54 49](https://user-images.githubusercontent.com/22156512/41761009-69f0231e-7613-11e8-91a5-dc77069b15db.png)

This was the example code given by the cornerstone library , I am trying to edit the code respectively , but the output is to no avail

**Comment by rahulbhatia123** [comment]
Could you just give me an example code if you don't mind , I am not sure how to write the exact code for my image loader and the respective image id for that

**Comment by Im-Goutham** [comment]
Is .dcm file set of multiple images or a single image ?

**Comment by Im-Goutham** [comment]
@dannyrb  Hi Please share some sample how we can implement scroll for dicom images ?

**Comment by dannyrb** [comment]
@Im-Goutham if you have an unrelated question, please create a new topic.

I'm locking this. This topic seems to garner a lot of misc. comments/questions. If you're reading this and have any questions, please create a new topic with a descriptive title.
